# Generated by Django 3.0.8 on 2020-07-16 20:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain_name', models.CharField(max_length=254)),
                ('description', models.CharField(max_length=254)),
                ('user_email', models.EmailField(max_length=254)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('additional_info', models.CharField(blank=True, max_length=254)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Website Information',
                'verbose_name_plural': 'Websites Information',
            },
        ),
        migrations.CreateModel(
            name='BlockedSites',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_blocked', models.BooleanField(default=False, verbose_name='Want to block it?')),
                ('email_was_sent', models.BooleanField(default=False, verbose_name='User was notified')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sites.UserRequest')),
            ],
            options={
                'verbose_name': 'Blocked Website',
                'verbose_name_plural': 'Blocked Websites',
                'unique_together': {('is_blocked', 'site')},
            },
        ),
    ]
